"""initial generated app schema

Revision ID: 0001_initial_schema
Revises:
Create Date: generated by Launch Kit
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "app_settings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("key", sa.String(length=150), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("value_type", sa.String(length=50), nullable=False),
        sa.Column("group", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_secret", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_app_settings_key"), "app_settings", ["key"], unique=True)

    op.create_table(
        "appointments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("appointment_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("client_name", sa.String(length=220), nullable=False),
        sa.Column("client_email", sa.String(length=320), nullable=False),
        sa.Column("client_phone", sa.String(length=80), nullable=True),
        sa.Column("service_id", sa.String(), nullable=True),
        sa.Column("therapist_profile_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("session_format", sa.String(length=220), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("client_message", sa.Text(), nullable=True),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "availability_exceptions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("exception_type", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("service_id", sa.String(), nullable=True),
        sa.Column("therapist_profile_id", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "availability_rules",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=220), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("slot_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("buffer_minutes", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.String(), nullable=True),
        sa.Column("therapist_profile_id", sa.String(), nullable=True),
        sa.Column("session_format", sa.String(length=220), nullable=True),
        sa.Column("location", sa.String(length=220), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "blog_posts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=220), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("body_markdown", sa.Text(), nullable=False),
        sa.Column("cover_image_url", sa.String(length=500), nullable=True),
        sa.Column("cover_image_alt", sa.String(length=220), nullable=True),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("author_name", sa.String(length=180), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("seo_title", sa.String(length=220), nullable=True),
        sa.Column("seo_description", sa.String(length=320), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("status IN ('draft', 'published')", name="ck_blog_posts_status"),
    )

    op.create_index(op.f("ix_blog_posts_published_at"), "blog_posts", ["published_at"], unique=False)

    op.create_index(op.f("ix_blog_posts_slug"), "blog_posts", ["slug"], unique=True)

    op.create_index(op.f("ix_blog_posts_status"), "blog_posts", ["status"], unique=False)

    op.create_table(
        "booking_holds",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("hold_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("service_id", sa.String(), nullable=True),
        sa.Column("therapist_profile_id", sa.String(), nullable=True),
        sa.Column("session_format", sa.String(length=220), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("client_name", sa.String(length=220), nullable=True),
        sa.Column("client_email", sa.String(length=320), nullable=True),
        sa.Column("client_phone", sa.String(length=80), nullable=True),
        sa.Column("payment_policy_snapshot", sa.String(length=40), nullable=True),
        sa.Column("confirmation_mode_snapshot", sa.String(length=40), nullable=True),
        sa.Column("quoted_price_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("advance_payment_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("payment_currency", sa.String(length=3), nullable=True),
        sa.Column("deposit_percentage_snapshot", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("appointment_id", sa.String(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("advance_payment_amount IS NULL OR advance_payment_amount > 0", name="ck_booking_holds_advance_payment_positive"),
        sa.CheckConstraint("deposit_percentage_snapshot IS NULL OR (deposit_percentage_snapshot >= 1 AND deposit_percentage_snapshot <= 99)", name="ck_booking_holds_deposit_percentage_range"),
        sa.CheckConstraint("quoted_price_amount IS NULL OR quoted_price_amount >= 0", name="ck_booking_holds_quoted_price_non_negative"),
    )

    op.create_table(
        "booking_settings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("payment_policy", sa.String(length=30), nullable=False),
        sa.Column("deposit_percentage", sa.Integer(), nullable=True),
        sa.Column("confirmation_mode", sa.String(length=30), nullable=False),
        sa.Column("recommended_payment_provider", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("confirmation_mode IN ('instant', 'staff_approval')", name="ck_booking_settings_confirmation_mode"),
        sa.CheckConstraint("deposit_percentage IS NULL OR (deposit_percentage >= 1 AND deposit_percentage <= 99)", name="ck_booking_settings_deposit_percentage"),
        sa.CheckConstraint("(payment_policy = 'deposit' AND deposit_percentage IS NOT NULL) OR (payment_policy != 'deposit' AND deposit_percentage IS NULL)", name="ck_booking_settings_deposit_policy"),
        sa.CheckConstraint("payment_policy IN ('none', 'pay_later', 'deposit', 'full_upfront')", name="ck_booking_settings_payment_policy"),
    )

    op.create_table(
        "client_records",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("client_number", sa.String(length=80), nullable=False),
        sa.Column("full_name", sa.String(length=220), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("phone", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("preferred_contact_method", sa.String(length=80), nullable=False),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_client_records_email"),
    )

    op.create_index(op.f("ix_client_records_client_number"), "client_records", ["client_number"], unique=True)

    op.create_index(op.f("ix_client_records_email"), "client_records", ["email"], unique=False)

    op.create_index(op.f("ix_client_records_source"), "client_records", ["source"], unique=False)

    op.create_index(op.f("ix_client_records_status"), "client_records", ["status"], unique=False)

    op.create_table(
        "commerce_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=220), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("item_type", sa.String(length=80), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=160), nullable=True),
        sa.Column("linked_service_id", sa.String(), nullable=True),
        sa.Column("price_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("sku", sa.String(length=120), nullable=True),
        sa.Column("stock_quantity", sa.Integer(), nullable=True),
        sa.Column("session_credit_count", sa.Integer(), nullable=True),
        sa.Column("fulfillment_type", sa.String(length=80), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_commerce_items_slug"), "commerce_items", ["slug"], unique=True)

    op.create_table(
        "commerce_orders",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("order_number", sa.String(length=80), nullable=False),
        sa.Column("customer_name", sa.String(length=220), nullable=False),
        sa.Column("customer_email", sa.String(length=320), nullable=False),
        sa.Column("customer_phone", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column("fulfillment_status", sa.String(length=80), nullable=False),
        sa.Column("subtotal_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_commerce_orders_order_number"), "commerce_orders", ["order_number"], unique=True)

    op.create_table(
        "contact_messages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=220), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "email_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("to_email", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_email_logs_status"), "email_logs", ["status"], unique=False)

    op.create_index(op.f("ix_email_logs_to_email"), "email_logs", ["to_email"], unique=False)

    op.create_table(
        "email_templates",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("key", sa.String(length=150), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_email_templates_key"), "email_templates", ["key"], unique=True)

    op.create_table(
        "landing_sections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("key", sa.String(length=150), nullable=False),
        sa.Column("title", sa.String(length=220), nullable=False),
        sa.Column("eyebrow", sa.String(length=180), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("cta_label", sa.String(length=120), nullable=True),
        sa.Column("cta_url", sa.String(length=500), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_landing_sections_key"), "landing_sections", ["key"], unique=True)

    op.create_table(
        "permissions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_permissions_code"), "permissions", ["code"], unique=True)

    op.create_table(
        "roles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)

    op.create_table(
        "services",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=220), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=160), nullable=True),
        sa.Column("service_format", sa.String(length=220), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("price_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("payment_policy_override", sa.String(length=30), nullable=True),
        sa.Column("deposit_percentage_override", sa.Integer(), nullable=True),
        sa.Column("confirmation_mode_override", sa.String(length=30), nullable=True),
        sa.Column("cta_label", sa.String(length=120), nullable=True),
        sa.Column("cta_url", sa.String(length=500), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("confirmation_mode_override IS NULL OR confirmation_mode_override IN ('instant', 'staff_approval')", name="ck_services_confirmation_mode_override"),
        sa.CheckConstraint("(payment_policy_override = 'deposit' AND deposit_percentage_override IS NOT NULL) OR ((payment_policy_override IS NULL OR payment_policy_override != 'deposit') AND deposit_percentage_override IS NULL)", name="ck_services_deposit_override_policy"),
        sa.CheckConstraint("deposit_percentage_override IS NULL OR (deposit_percentage_override >= 1 AND deposit_percentage_override <= 99)", name="ck_services_deposit_percentage_override"),
        sa.CheckConstraint("payment_policy_override IS NULL OR payment_policy_override IN ('none', 'pay_later', 'deposit', 'full_upfront')", name="ck_services_payment_policy_override"),
    )

    op.create_index(op.f("ix_services_slug"), "services", ["slug"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    op.create_table(
        "client_record_links",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("client_record_id", sa.String(), nullable=False),
        sa.Column("link_type", sa.String(length=80), nullable=False),
        sa.Column("linked_record_id", sa.String(), nullable=False),
        sa.Column("label", sa.String(length=220), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["client_record_id"], ["client_records.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_record_id", "link_type", "linked_record_id", name="uq_client_record_links_record"),
    )

    op.create_index(op.f("ix_client_record_links_client_record_id"), "client_record_links", ["client_record_id"], unique=False)

    op.create_index(op.f("ix_client_record_links_link_type"), "client_record_links", ["link_type"], unique=False)

    op.create_index(op.f("ix_client_record_links_linked_record_id"), "client_record_links", ["linked_record_id"], unique=False)

    op.create_table(
        "commerce_order_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("order_id", sa.String(), nullable=False),
        sa.Column("commerce_item_id", sa.String(), nullable=True),
        sa.Column("item_name", sa.String(length=220), nullable=False),
        sa.Column("item_type", sa.String(length=80), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("line_total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("linked_service_id", sa.String(), nullable=True),
        sa.Column("session_credit_count", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["commerce_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "email_verification_tokens",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_email_verification_tokens_token_hash"), "email_verification_tokens", ["token_hash"], unique=True)

    op.create_index(op.f("ix_email_verification_tokens_user_id"), "email_verification_tokens", ["user_id"], unique=False)

    op.create_table(
        "files",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_provider", sa.String(length=80), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("uploaded_by_user_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["uploaded_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "invitations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("pending_email_key", sa.String(length=255), nullable=True),
        sa.Column("role_name", sa.String(length=100), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("delivery_status", sa.String(length=40), nullable=False),
        sa.Column("invited_by_user_id", sa.String(), nullable=False),
        sa.Column("accepted_by_user_id", sa.String(), nullable=True),
        sa.Column("revoked_by_user_id", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("expired_at", sa.DateTime(), nullable=True),
        sa.Column("last_sent_at", sa.DateTime(), nullable=False),
        sa.Column("send_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["accepted_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["invited_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["revoked_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("(status = 'accepted' AND accepted_at IS NOT NULL AND accepted_by_user_id IS NOT NULL) OR (status <> 'accepted' AND accepted_at IS NULL AND accepted_by_user_id IS NULL)", name="ck_invitations_accepted_state"),
        sa.CheckConstraint("delivery_status IN ('queued', 'sent', 'failed')", name="ck_invitations_delivery_status"),
        sa.CheckConstraint("(status = 'expired' AND expired_at IS NOT NULL) OR (status <> 'expired' AND expired_at IS NULL)", name="ck_invitations_expired_state"),
        sa.CheckConstraint("(status = 'pending' AND token_hash IS NOT NULL AND pending_email_key IS NOT NULL) OR (status <> 'pending' AND token_hash IS NULL AND pending_email_key IS NULL)", name="ck_invitations_pending_secrets"),
        sa.CheckConstraint("(status = 'revoked' AND revoked_at IS NOT NULL AND revoked_by_user_id IS NOT NULL) OR (status <> 'revoked' AND revoked_at IS NULL AND revoked_by_user_id IS NULL)", name="ck_invitations_revoked_state"),
        sa.CheckConstraint("status IN ('pending', 'accepted', 'revoked', 'expired')", name="ck_invitations_status"),
        sa.UniqueConstraint("pending_email_key", name="uq_invitations_pending_email_key"),
        sa.UniqueConstraint("token_hash", name="uq_invitations_token_hash"),
    )

    op.create_index(op.f("ix_invitations_delivery_status"), "invitations", ["delivery_status"], unique=False)

    op.create_index(op.f("ix_invitations_email"), "invitations", ["email"], unique=False)

    op.create_index(op.f("ix_invitations_role_name"), "invitations", ["role_name"], unique=False)

    op.create_index(op.f("ix_invitations_status"), "invitations", ["status"], unique=False)

    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_password_reset_tokens_token_hash"), "password_reset_tokens", ["token_hash"], unique=True)

    op.create_index(op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False)

    op.create_table(
        "payment_requests",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("request_number", sa.String(length=80), nullable=False),
        sa.Column("commerce_order_id", sa.String(), nullable=True),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("customer_name", sa.String(length=220), nullable=False),
        sa.Column("customer_email", sa.String(length=320), nullable=False),
        sa.Column("customer_phone", sa.String(length=80), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("provider_reference", sa.String(length=255), nullable=True),
        sa.Column("provider_transaction_reference", sa.String(length=255), nullable=True),
        sa.Column("settlement_account_label", sa.String(length=160), nullable=True),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["commerce_order_id"], ["commerce_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("((target_type = 'commerce_order' AND commerce_order_id IS NOT NULL AND target_id = commerce_order_id) OR (target_type = 'booking_hold' AND commerce_order_id IS NULL))", name="ck_payment_requests_target_shape"),
    )

    op.create_index(op.f("ix_payment_requests_request_number"), "payment_requests", ["request_number"], unique=True)

    op.create_index(op.f("ix_payment_requests_status"), "payment_requests", ["status"], unique=False)

    op.create_index(op.f("ix_payment_requests_target"), "payment_requests", ["target_type", "target_id"], unique=False)

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True)

    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)

    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.String(), nullable=False),
        sa.Column("permission_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )

    op.create_table(
        "therapist_profiles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(length=220), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("title", sa.String(length=220), nullable=True),
        sa.Column("short_bio", sa.Text(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("specialties", sa.Text(), nullable=True),
        sa.Column("approaches", sa.Text(), nullable=True),
        sa.Column("languages", sa.String(length=500), nullable=True),
        sa.Column("location", sa.String(length=220), nullable=True),
        sa.Column("session_formats", sa.String(length=500), nullable=True),
        sa.Column("profile_image_url", sa.String(length=500), nullable=True),
        sa.Column("booking_cta_label", sa.String(length=120), nullable=True),
        sa.Column("booking_cta_url", sa.String(length=500), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("reviewed_by_user_id", sa.String(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["reviewed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("review_status IN ('draft', 'pending_review', 'changes_requested', 'approved')", name="ck_therapist_profiles_review_status"),
    )

    op.create_index(op.f("ix_therapist_profiles_review_status"), "therapist_profiles", ["review_status"], unique=False)

    op.create_index(op.f("ix_therapist_profiles_slug"), "therapist_profiles", ["slug"], unique=True)

    op.create_index(op.f("ix_therapist_profiles_user_id"), "therapist_profiles", ["user_id"], unique=True)

    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("role_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )

    op.create_table(
        "booking_schedule_locks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("therapist_profile_id", sa.String(), nullable=False),
        sa.Column("schedule_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["therapist_profile_id"], ["therapist_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("therapist_profile_id", "schedule_date", name="uq_booking_schedule_locks_therapist_date"),
    )

    op.create_table(
        "payment_attempts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("attempt_number", sa.String(length=80), nullable=False),
        sa.Column("payment_request_id", sa.String(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("provider_reference", sa.String(length=255), nullable=True),
        sa.Column("provider_transaction_reference", sa.String(length=255), nullable=True),
        sa.Column("provider_session_id", sa.String(length=255), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column("verification_status", sa.String(length=80), nullable=False),
        sa.Column("checkout_url", sa.String(length=500), nullable=True),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("initiated_by_user_id", sa.String(), nullable=True),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["payment_request_id"], ["payment_requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
        sa.UniqueConstraint("provider", "provider_reference", name="uq_payment_attempts_provider_reference"),
    )

    op.create_index(op.f("ix_payment_attempts_attempt_number"), "payment_attempts", ["attempt_number"], unique=True)

    op.create_index(op.f("ix_payment_attempts_payment_request_id"), "payment_attempts", ["payment_request_id"], unique=False)

    op.create_index(op.f("ix_payment_attempts_provider"), "payment_attempts", ["provider"], unique=False)

    op.create_index(op.f("ix_payment_attempts_status"), "payment_attempts", ["status"], unique=False)

    op.create_table(
        "payment_request_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("payment_request_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("from_status", sa.String(length=80), nullable=True),
        sa.Column("to_status", sa.String(length=80), nullable=True),
        sa.Column("provider", sa.String(length=80), nullable=True),
        sa.Column("provider_reference", sa.String(length=255), nullable=True),
        sa.Column("provider_transaction_reference", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("actor_user_id", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["payment_request_id"], ["payment_requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_payment_request_events_payment_request_id"), "payment_request_events", ["payment_request_id"], unique=False)

    op.create_table(
        "receipt_records",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("receipt_number", sa.String(length=80), nullable=False),
        sa.Column("payment_request_id", sa.String(), nullable=False),
        sa.Column("payment_reference", sa.String(length=80), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("commerce_order_id", sa.String(), nullable=True),
        sa.Column("appointment_id", sa.String(), nullable=True),
        sa.Column("customer_name", sa.String(length=255), nullable=False),
        sa.Column("customer_email", sa.String(length=255), nullable=False),
        sa.Column("customer_phone", sa.String(length=80), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("provider_reference", sa.String(length=255), nullable=True),
        sa.Column("provider_transaction_reference", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("issued_at", sa.DateTime(), nullable=False),
        sa.Column("voided_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["commerce_order_id"], ["commerce_orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["payment_request_id"], ["payment_requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("(appointment_id IS NULL OR target_type = 'booking_hold')", name="ck_receipt_records_appointment_target"),
        sa.CheckConstraint("((target_type = 'commerce_order' AND commerce_order_id IS NOT NULL AND target_id = commerce_order_id) OR (target_type = 'booking_hold' AND commerce_order_id IS NULL))", name="ck_receipt_records_target_shape"),
        sa.UniqueConstraint("payment_request_id", name="uq_receipt_records_payment_request_id"),
    )

    op.create_index(op.f("ix_receipt_records_appointment_id"), "receipt_records", ["appointment_id"], unique=False)

    op.create_index(op.f("ix_receipt_records_commerce_order_id"), "receipt_records", ["commerce_order_id"], unique=False)

    op.create_index(op.f("ix_receipt_records_customer_email"), "receipt_records", ["customer_email"], unique=False)

    op.create_index(op.f("ix_receipt_records_payment_reference"), "receipt_records", ["payment_reference"], unique=True)

    op.create_index(op.f("ix_receipt_records_payment_request_id"), "receipt_records", ["payment_request_id"], unique=False)

    op.create_index(op.f("ix_receipt_records_receipt_number"), "receipt_records", ["receipt_number"], unique=True)

    op.create_index(op.f("ix_receipt_records_status"), "receipt_records", ["status"], unique=False)

    op.create_index(op.f("ix_receipt_records_target"), "receipt_records", ["target_type", "target_id"], unique=False)

    op.create_table(
        "therapist_profile_revisions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("therapist_profile_id", sa.String(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("short_bio", sa.Text(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("specialties", sa.Text(), nullable=True),
        sa.Column("approaches", sa.Text(), nullable=True),
        sa.Column("languages", sa.Text(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("session_formats", sa.Text(), nullable=True),
        sa.Column("profile_image_url", sa.String(length=500), nullable=True),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("reviewed_by_user_id", sa.String(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("is_current_publication", sa.Boolean(), nullable=False),
        sa.Column("published_by_user_id", sa.String(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["published_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reviewed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["therapist_profile_id"], ["therapist_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("review_status IN ('draft', 'pending_review', 'changes_requested', 'approved')", name="ck_therapist_profile_revisions_review_status"),
        sa.UniqueConstraint("therapist_profile_id", "version_number", name="uq_therapist_profile_revision_version"),
    )

    op.create_index(op.f("ix_therapist_profile_revisions_is_current_publication"), "therapist_profile_revisions", ["is_current_publication"], unique=False)

    op.create_index(op.f("ix_therapist_profile_revisions_review_status"), "therapist_profile_revisions", ["review_status"], unique=False)

    op.create_index(op.f("ix_therapist_profile_revisions_therapist_profile_id"), "therapist_profile_revisions", ["therapist_profile_id"], unique=False)

    op.create_table(
        "fulfillment_records",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("fulfillment_number", sa.String(length=80), nullable=False),
        sa.Column("receipt_id", sa.String(), nullable=False),
        sa.Column("payment_request_id", sa.String(), nullable=False),
        sa.Column("commerce_order_id", sa.String(), nullable=False),
        sa.Column("order_number", sa.String(length=80), nullable=False),
        sa.Column("customer_name", sa.String(length=255), nullable=False),
        sa.Column("customer_email", sa.String(length=255), nullable=False),
        sa.Column("customer_phone", sa.String(length=80), nullable=True),
        sa.Column("fulfillment_type", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("fulfilled_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["commerce_order_id"], ["commerce_orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["payment_request_id"], ["payment_requests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipt_records.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("commerce_order_id", name="uq_fulfillment_records_commerce_order_id"),
        sa.UniqueConstraint("receipt_id", name="uq_fulfillment_records_receipt_id"),
    )

    op.create_index(op.f("ix_fulfillment_records_commerce_order_id"), "fulfillment_records", ["commerce_order_id"], unique=False)

    op.create_index(op.f("ix_fulfillment_records_customer_email"), "fulfillment_records", ["customer_email"], unique=False)

    op.create_index(op.f("ix_fulfillment_records_fulfillment_number"), "fulfillment_records", ["fulfillment_number"], unique=True)

    op.create_index(op.f("ix_fulfillment_records_fulfillment_type"), "fulfillment_records", ["fulfillment_type"], unique=False)

    op.create_index(op.f("ix_fulfillment_records_payment_request_id"), "fulfillment_records", ["payment_request_id"], unique=False)

    op.create_index(op.f("ix_fulfillment_records_receipt_id"), "fulfillment_records", ["receipt_id"], unique=False)

    op.create_index(op.f("ix_fulfillment_records_status"), "fulfillment_records", ["status"], unique=False)

    op.create_table(
        "payment_provider_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("payment_attempt_id", sa.String(), nullable=True),
        sa.Column("payment_request_id", sa.String(), nullable=True),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("provider_reference", sa.String(length=255), nullable=True),
        sa.Column("provider_transaction_reference", sa.String(length=255), nullable=True),
        sa.Column("external_event_id", sa.String(length=255), nullable=True),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("event_status", sa.String(length=80), nullable=False),
        sa.Column("verification_status", sa.String(length=80), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("event_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=128), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column("is_duplicate", sa.Boolean(), nullable=False),
        sa.Column("original_event_id", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["payment_attempt_id"], ["payment_attempts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["payment_request_id"], ["payment_requests.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_payment_provider_events_event_fingerprint"), "payment_provider_events", ["event_fingerprint"], unique=False)

    op.create_index(op.f("ix_payment_provider_events_payment_attempt_id"), "payment_provider_events", ["payment_attempt_id"], unique=False)

    op.create_index(op.f("ix_payment_provider_events_payment_request_id"), "payment_provider_events", ["payment_request_id"], unique=False)

    op.create_index(op.f("ix_payment_provider_events_provider"), "payment_provider_events", ["provider"], unique=False)

    op.create_table(
        "receipt_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("receipt_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("from_status", sa.String(length=80), nullable=True),
        sa.Column("to_status", sa.String(length=80), nullable=True),
        sa.Column("actor_user_id", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipt_records.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_receipt_events_receipt_id"), "receipt_events", ["receipt_id"], unique=False)

    op.create_table(
        "fulfillment_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("fulfillment_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("from_status", sa.String(length=80), nullable=True),
        sa.Column("to_status", sa.String(length=80), nullable=True),
        sa.Column("actor_user_id", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["fulfillment_id"], ["fulfillment_records.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_fulfillment_events_fulfillment_id"), "fulfillment_events", ["fulfillment_id"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_fulfillment_events_fulfillment_id"), table_name="fulfillment_events")
    op.drop_table("fulfillment_events")
    op.drop_index(op.f("ix_receipt_events_receipt_id"), table_name="receipt_events")
    op.drop_table("receipt_events")
    op.drop_index(op.f("ix_payment_provider_events_provider"), table_name="payment_provider_events")
    op.drop_index(op.f("ix_payment_provider_events_payment_request_id"), table_name="payment_provider_events")
    op.drop_index(op.f("ix_payment_provider_events_payment_attempt_id"), table_name="payment_provider_events")
    op.drop_index(op.f("ix_payment_provider_events_event_fingerprint"), table_name="payment_provider_events")
    op.drop_table("payment_provider_events")
    op.drop_index(op.f("ix_fulfillment_records_status"), table_name="fulfillment_records")
    op.drop_index(op.f("ix_fulfillment_records_receipt_id"), table_name="fulfillment_records")
    op.drop_index(op.f("ix_fulfillment_records_payment_request_id"), table_name="fulfillment_records")
    op.drop_index(op.f("ix_fulfillment_records_fulfillment_type"), table_name="fulfillment_records")
    op.drop_index(op.f("ix_fulfillment_records_fulfillment_number"), table_name="fulfillment_records")
    op.drop_index(op.f("ix_fulfillment_records_customer_email"), table_name="fulfillment_records")
    op.drop_index(op.f("ix_fulfillment_records_commerce_order_id"), table_name="fulfillment_records")
    op.drop_table("fulfillment_records")
    op.drop_index(op.f("ix_therapist_profile_revisions_therapist_profile_id"), table_name="therapist_profile_revisions")
    op.drop_index(op.f("ix_therapist_profile_revisions_review_status"), table_name="therapist_profile_revisions")
    op.drop_index(op.f("ix_therapist_profile_revisions_is_current_publication"), table_name="therapist_profile_revisions")
    op.drop_table("therapist_profile_revisions")
    op.drop_index(op.f("ix_receipt_records_target"), table_name="receipt_records")
    op.drop_index(op.f("ix_receipt_records_status"), table_name="receipt_records")
    op.drop_index(op.f("ix_receipt_records_receipt_number"), table_name="receipt_records")
    op.drop_index(op.f("ix_receipt_records_payment_request_id"), table_name="receipt_records")
    op.drop_index(op.f("ix_receipt_records_payment_reference"), table_name="receipt_records")
    op.drop_index(op.f("ix_receipt_records_customer_email"), table_name="receipt_records")
    op.drop_index(op.f("ix_receipt_records_commerce_order_id"), table_name="receipt_records")
    op.drop_index(op.f("ix_receipt_records_appointment_id"), table_name="receipt_records")
    op.drop_table("receipt_records")
    op.drop_index(op.f("ix_payment_request_events_payment_request_id"), table_name="payment_request_events")
    op.drop_table("payment_request_events")
    op.drop_index(op.f("ix_payment_attempts_status"), table_name="payment_attempts")
    op.drop_index(op.f("ix_payment_attempts_provider"), table_name="payment_attempts")
    op.drop_index(op.f("ix_payment_attempts_payment_request_id"), table_name="payment_attempts")
    op.drop_index(op.f("ix_payment_attempts_attempt_number"), table_name="payment_attempts")
    op.drop_table("payment_attempts")
    op.drop_table("booking_schedule_locks")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_therapist_profiles_user_id"), table_name="therapist_profiles")
    op.drop_index(op.f("ix_therapist_profiles_slug"), table_name="therapist_profiles")
    op.drop_index(op.f("ix_therapist_profiles_review_status"), table_name="therapist_profiles")
    op.drop_table("therapist_profiles")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_payment_requests_target"), table_name="payment_requests")
    op.drop_index(op.f("ix_payment_requests_status"), table_name="payment_requests")
    op.drop_index(op.f("ix_payment_requests_request_number"), table_name="payment_requests")
    op.drop_table("payment_requests")
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_index(op.f("ix_password_reset_tokens_token_hash"), table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_index(op.f("ix_invitations_status"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_role_name"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_email"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_delivery_status"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_table("files")
    op.drop_index(op.f("ix_email_verification_tokens_user_id"), table_name="email_verification_tokens")
    op.drop_index(op.f("ix_email_verification_tokens_token_hash"), table_name="email_verification_tokens")
    op.drop_table("email_verification_tokens")
    op.drop_table("commerce_order_items")
    op.drop_index(op.f("ix_client_record_links_linked_record_id"), table_name="client_record_links")
    op.drop_index(op.f("ix_client_record_links_link_type"), table_name="client_record_links")
    op.drop_index(op.f("ix_client_record_links_client_record_id"), table_name="client_record_links")
    op.drop_table("client_record_links")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_services_slug"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_code"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_landing_sections_key"), table_name="landing_sections")
    op.drop_table("landing_sections")
    op.drop_index(op.f("ix_email_templates_key"), table_name="email_templates")
    op.drop_table("email_templates")
    op.drop_index(op.f("ix_email_logs_to_email"), table_name="email_logs")
    op.drop_index(op.f("ix_email_logs_status"), table_name="email_logs")
    op.drop_table("email_logs")
    op.drop_table("contact_messages")
    op.drop_index(op.f("ix_commerce_orders_order_number"), table_name="commerce_orders")
    op.drop_table("commerce_orders")
    op.drop_index(op.f("ix_commerce_items_slug"), table_name="commerce_items")
    op.drop_table("commerce_items")
    op.drop_index(op.f("ix_client_records_status"), table_name="client_records")
    op.drop_index(op.f("ix_client_records_source"), table_name="client_records")
    op.drop_index(op.f("ix_client_records_email"), table_name="client_records")
    op.drop_index(op.f("ix_client_records_client_number"), table_name="client_records")
    op.drop_table("client_records")
    op.drop_table("booking_settings")
    op.drop_table("booking_holds")
    op.drop_index(op.f("ix_blog_posts_status"), table_name="blog_posts")
    op.drop_index(op.f("ix_blog_posts_slug"), table_name="blog_posts")
    op.drop_index(op.f("ix_blog_posts_published_at"), table_name="blog_posts")
    op.drop_table("blog_posts")
    op.drop_table("availability_rules")
    op.drop_table("availability_exceptions")
    op.drop_table("appointments")
    op.drop_index(op.f("ix_app_settings_key"), table_name="app_settings")
    op.drop_table("app_settings")
